repos:
# Python format and lint with Ruff
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

# Check for large files, binary files, private keys
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files  # Prevents giant data files
    -   id: check-yaml              # Validates YAML files
    -   id: check-json             # Validates JSON files
    -   id: check-case-conflict    # Checks for files that would conflict in case-insensitive systems
    -   id: check-merge-conflict   # Checks for files that contain merge conflict strings
    -   id: detect-private-key     # Checks for presence of private keys
    -   id: end-of-file-fixer     # Makes sure files end in a newline
    -   id: trailing-whitespace    # Trims trailing whitespace

# Check for common security issues
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa  # Enforce specific noqa comments
    -   id: python-no-eval            # Prevent use of eval()
    -   id: python-no-log-warn        # Use warning() instead of warn()
# Update to newer language version features
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
